### ISSUE TITLE
Support GeoSpatial Queries

### ISSUE THREAD

**Issue by brainbuz** [petdance/webservice-solr#19]
I couldn't find anything in the documentation specific to geospatial queries.

It wasn't hard to generate an appropriate string to pass to fq. I could easily turn my code into a method. Probably the most consistent thing would be to create a method in the Query submodule.

**Comment by brainbuz** [comment]
Closing inactive issue, I'm no longer working on the project that prompted this.

**Comment by petdance** [comment]
Thanks for helping keep things tidy.
